# Generated by Django 6.0.6 on 2026-06-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('due_date', models.DateField(null=True)),
                ('task_image', models.ImageField(null=True, upload_to='media/tasks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
